Feature/add article crud
our-baby/mommy pull request #5
Opened 2024-04-04 14:16 UTC by rjwharry

### 개요
Resolves #1 #2 #3    
Article CRUD API 개발

### 기능설명 OR 해결방법
- Article CRUD API 개발
- BaseEntity(createdAt, updatedAt) 추가, 자동으로 시간 반영
- ExceptionControllerAdvice 추가

2024-04-07 10:42 UTC, ybkim-dev requested changes
재원님 고생하셨습니다.
리뷰 확인해보시고 수정할 부분들 수정 부탁드려요.
수정 후에 다시 리뷰해서 Approve 하겠습니다.

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/controller/ArticleController.kt
> +	}
List ~ return 제거하고 `=` 으로 처리

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/controller/ArticleController.kt
> +	}
동일. 밑에 Mapping 들도

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/controller/ArticleController.kt
> +	@PostMapping("")
PostMapping만 쓰면 됨 ""없이

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/controller/ArticleController.kt
> +		@RequestBody body: ArticleRequestDto
변수명 body 대신 articleRequestDto 어떰?

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/dto/ArticleRequestDto.kt
> +	fun toEntity(): ArticleEntity {
어차피 ArticleEntity 생성만 할거면 `=`

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/controller/ArticleController.kt
> +}
46번라인 밑에 빈줄 하나 추가해서 - 기호 없애기

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/controller/ArticleController.kt
> +}
다른 클래스들도 모두 그렇게 적용

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/persistence/entity/ArticleEntity.kt
> +	@Id @GeneratedValue(strategy = GenerationType.IDENTITY)
가능하면 어노테이션들은 한 줄에 하나씩만!
그리고 GenerationType.IDENTITY 가 아니라 IDENTITY만 쓰도록 static import ㄱㄱ

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/persistence/entity/ArticleEntity.kt
> +	val id: Long? = null,
? = null 빼도 될듯
어차피 자동으로 잡아줄텐데 JPA에서

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/persistence/entity/ArticleEntity.kt
> +	@Column(columnDefinition = "TEXT")
columnDefinition은 어떤 역할임?
빼도 될거 같은데

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/persistence/entity/ArticleEntity.kt
> +	fun toDto(): ArticleResponseDto {
=

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/service/ArticleService.kt
> +	}
= 처리

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/article/service/ArticleService.kt
> +	fun getArticleById(id: Long): ArticleEntity {
이거 .get 없어도 되지 않나?

 = articleRepository.findById(id) ?: throw NoSuchElementException()

2024-04-07 10:42 UTC, ybkim-dev commented on src/main/kotlin/com/highschool/ourbaby/core/exception/GlobalControllerAdvice.kt
> +			HttpStatus.NOT_FOUND.value(),
static import

2024-04-07 13:10 UTC, rjwharry commented on src/main/kotlin/com/highschool/ourbaby/article/persistence/entity/ArticleEntity.kt
> +	@Column(columnDefinition = "TEXT")
그냥 string하면 mysql 데이터 타입이 의도대로 안들어갈 거 같아서 확실하게 하려고 넣었음

2024-04-07 13:11 UTC, rjwharry commented on src/main/kotlin/com/highschool/ourbaby/article/service/ArticleService.kt
> +	fun getArticleById(id: Long): ArticleEntity {
findById가 null일 때 .get하면 NoSuchElementException 에러가 발생해서 이렇게 했는데,
코틀린 방식으로 하는게 좋을듯. 고치겠음

2024-04-07 13:26 UTC, rjwharry commented on src/main/kotlin/com/highschool/ourbaby/article/service/ArticleService.kt
> +	fun getArticleById(id: Long): ArticleEntity {
아 근데 findById의 리턴 타입이 Optional<ArticleEntity>여서, 그래서 get함수 호출했었음

2024-04-07 13:30 UTC, rjwharry commented on src/main/kotlin/com/highschool/ourbaby/article/service/ArticleService.kt
> +	fun getArticleById(id: Long): ArticleEntity {
```kotlin
articleRepository.findById(id).getOrNull() ?: throw NoSuchElementException()
```
이렇게 해야되나?

2024-04-11 13:23 UTC, ybkim-dev approved these changes

2024-04-12 15:11 UTC, merged